apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Variables d'environnement pour le backend
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "transporteur"
  DB_USERNAME: "root"
  
  # # Variables MinIO
  # MINIO_ENDPOINT: "minio-service"
  # MINIO_PORT: "9000"
  # MINIO_SSL: "false"
  
  # Variables pour le frontend
  NEXT_PUBLIC_API_URL: "http://backend-app-service:3001"

