apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbuyers-backend
spec:
  selector:
    matchLabels:
      app: carbuyers-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: carbuyers-backend
    spec:
      containers:
        - name: carbuyers-backend
          image: ghcr.io/brege-ng/first_app_argo_test_backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: carbuyers-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: carbuyers-secret
                  key: db-password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: carbuyers-secret
                  key: app-key

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: carbuyers-backend-service
spec:
  type: LoadBalancer
  selector:
    app: carbuyers-backend
  ports:
    - name: http
      port: 4201
      targetPort: 8000
