apiVersion: v1
kind: ConfigMap
metadata:
  name: carbuyers-config
data:
  # Application
  APP_NAME: "AutoDrive"
  APP_ENV: "production"
  APP_DEBUG: "false"

  # Variables d'environnement pour le backend
  DB_CONNECTION: "mysql"
  DB_HOST: "carbuyers-mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "laravel"
  DB_USERNAME: "laravel_user"

  # Variables pour le frontend
  NEXT_PUBLIC_URL: "http://127.0.0.1:4200"
  NEXT_PUBLIC_API_URL: "http://127.0.0.1:4201/api"

