apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbuyers-frontend
spec:
  selector:
    matchLabels:
      app: carbuyers-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: carbuyers-frontend
    spec:
      containers:
        - name: carbuyers-frontend
          image: ghcr.io/cabinet-ceipi/cg-ceipi-gestiontransporteur-frontend-admin:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: carbuyers-config
                  key: NEXT_PUBLIC_URL
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: carbuyers-config
                  key: NEXT_PUBLIC_API_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      imagePullSecrets:
        - name: ghcr-secret-auth

---
apiVersion: v1
kind: Service
metadata:
  name: carbuyers-frontend-service
spec:
  type: NodePort
  selector:
    app: carbuyers-frontend
  ports:
    - name: http
      port: 4200
      targetPort: 3000
